import { IOption } from './ui';

export const categoryOptions: IOption[] = [
  { value: 'academic-subjects', label: 'Academic Subjects' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'arts-design-and-media', label: 'Arts, Design and Media' },
  { value: 'business-and-management', label: 'Business and Management' },
  {
    value: 'community-and-social-services',
    label: 'Community and Social Services',
  },
  { value: 'computer-science-and-it', label: 'Computer Science and IT' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'for-kids-and-teens', label: 'For Kids and Teens' },
  { value: 'health-and-safety', label: 'Health and Safety' },
  { value: 'language-learning', label: 'Language Learning' },
  {
    value: 'lifestyle-and-entertainment',
    label: 'Lifestyle and Entertainment',
  },
  { value: 'other', label: 'Other' },
  { value: 'personal-development', label: 'Personal Development' },
  { value: 'teaching-and-learning', label: 'Teaching and Learning' },
  { value: 'technology-and-innovation', label: 'Technology and Innovation' },
  { value: 'test-preparation', label: 'Test Preparation' },
];

export const subcategoryOptions: Record<string, IOption[]> = {
  'academic-subjects': [
    {
      value: 'history-and-philosophy-of-science',
      label: 'History and Philosophy of Science',
    },
    {
      value: 'humanities-and-social-sciences',
      label: 'Humanities and Social Sciences',
    },
    {
      value: 'mathematics-and-statistics',
      label: 'Mathematics and Statistics',
    },
    {
      value: 'natural-and-physical-sciences',
      label: 'Natural and Physical Sciences',
    },
    { value: 'school-subjects', label: 'School Subjects' },
    {
      value: 'scientific-research-methodology',
      label: 'Scientific Research Methodology',
    },
  ],
  architecture: [
    { value: 'architectural-design', label: 'Architectural Design' },
    { value: 'interior-design', label: 'Interior Design' },
    { value: 'urban-planning', label: 'Urban Planning' },
  ],
  'arts-design-and-media': [
    { value: '3d-modeling', label: '3D Modeling' },
    {
      value: 'animation-and-motion-graphics',
      label: 'Animation and Motion Graphics',
    },
    { value: 'communication-design', label: 'Communication Design' },
    { value: 'computer-graphics', label: 'Computer Graphics' },
    { value: 'creative-writing', label: 'Creative Writing' },
    { value: 'fashion-design', label: 'Fashion Design' },
    { value: 'graphic-design', label: 'Graphic Design' },
    { value: 'illustrations', label: 'Illustrations' },
    { value: 'industrial-design', label: 'Industrial Design' },
    { value: 'interior-design', label: 'Interior Design' },
    { value: 'landscape-design', label: 'Landscape Design' },
    {
      value: 'music-and-audio-production',
      label: 'Music and Audio Production',
    },
    { value: 'photography', label: 'Photography' },
    { value: 'software-and-tools', label: 'Software and Tools' },
    { value: 'user-experience-design', label: 'User Experience Design' },
    {
      value: 'video-production-and-editing',
      label: 'Video Production and Editing',
    },
    {
      value: 'virtual-reality-and-augmented-reality',
      label: 'Virtual Reality and Augmented Reality',
    },
    { value: 'web-design', label: 'Web Design' },
  ],
  'business-and-management': [
    { value: 'business-analysis', label: 'Business Analysis' },
    { value: 'business-communication', label: 'Business Communication' },
    { value: 'business-development', label: 'Business Development' },
    { value: 'business-english', label: 'Business English' },
    { value: 'business-psychology', label: 'Business Psychology' },
    { value: 'e-commerce', label: 'E-commerce' },
    {
      value: 'electronic-document-management',
      label: 'Electronic Document Management',
    },
    { value: 'industry-specific-courses', label: 'Industry-Specific Courses' },
    { value: 'marketing', label: 'Marketing' },
    { value: 'project-management', label: 'Project Management' },
  ],
  'community-and-social-services': [
    { value: 'community-organizing', label: 'Community Organizing' },
    {
      value: 'fundraising-and-development',
      label: 'Fundraising and Development',
    },
    { value: 'nonprofit-management', label: 'Nonprofit Management' },
    { value: 'volunteering', label: 'Volunteering' },
  ],
  'computer-science-and-it': [
    {
      value: 'algorithms-and-data-structures',
      label: 'Algorithms and Data Structures',
    },
    { value: 'competitive-programming', label: 'Competitive Programming' },
    { value: 'computer-architecture', label: 'Computer Architecture' },
    { value: 'computer-networks', label: 'Computer Networks' },
    {
      value: 'cybersecurity-and-information-security',
      label: 'Cybersecurity and Information Security',
    },
    {
      value: 'data-science-and-analytics',
      label: 'Data Science and Analytics',
    },
    { value: 'database-systems', label: 'Database Systems' },
    { value: 'electronics-and-hardware', label: 'Electronics and Hardware' },
    { value: 'frameworks-and-libraries', label: 'Frameworks and Libraries' },
    {
      value: 'introduction-to-programming',
      label: 'Introduction to Programming',
    },
    { value: 'operating-systems', label: 'Operating Systems' },
    { value: 'programming-for-kids', label: 'Programming for Kids' },
    { value: 'programming-languages', label: 'Programming Languages' },
    { value: 'programming-paradigms', label: 'Programming Paradigms' },
    { value: 'software-and-tools', label: 'Software and Tools' },
    { value: 'software-development', label: 'Software Development' },
  ],
  engineering: [
    { value: 'aerospace-engineering', label: 'Aerospace Engineering' },
    { value: 'civil-engineering', label: 'Civil Engineering' },
    { value: 'electrical-engineering', label: 'Electrical Engineering' },
    {
      value: 'engineering-design-and-modeling',
      label: 'Engineering Design and Modeling',
    },
    { value: 'materials-science', label: 'Materials Science' },
    { value: 'mechanical-engineering', label: 'Mechanical Engineering' },
    { value: 'mechanics', label: 'Mechanics' },
    { value: 'optics', label: 'Optics' },
  ],
  'for-kids-and-teens': [
    // Add subcategories for "For Kids and Teens" if needed
  ],
  'health-and-safety': [
    {
      value: 'emergency-management-and-civil-defense',
      label: 'Emergency Management and Civil Defense',
    },
    { value: 'environmental-health', label: 'Environmental Health' },
    { value: 'first-aid', label: 'First Aid' },
    { value: 'food-safety', label: 'Food Safety' },
    { value: 'health-and-wellness', label: 'Health and Wellness' },
    { value: 'healthcare', label: 'Healthcare' },
    {
      value: 'mental-health-and-wellness',
      label: 'Mental Health and Wellness',
    },
    { value: 'occupational-health', label: 'Occupational Health' },
    { value: 'workplace-safety', label: 'Workplace Safety' },
  ],
  'language-learning': [
    { value: 'arabic', label: 'Arabic' },
    { value: 'chinese', label: 'Chinese' },
    { value: 'classical-languages', label: 'Classical Languages' },
    { value: 'english', label: 'English' },
    { value: 'french', label: 'French' },
    { value: 'german', label: 'German' },
    { value: 'italian', label: 'Italian' },
    { value: 'japanese', label: 'Japanese' },
    { value: 'korean', label: 'Korean' },
    { value: 'other-languages', label: 'Other Languages' },
    { value: 'russian', label: 'Russian' },
    { value: 'spanish', label: 'Spanish' },
    { value: 'turkish', label: 'Turkish' },
  ],
  'lifestyle-and-entertainment': [
    { value: 'animal-care', label: 'Animal Care' },
    { value: 'arts-and-crafts', label: 'Arts and Crafts' },
    { value: 'automotive-and-mechanics', label: 'Automotive and Mechanics' },
    { value: 'beauty-and-fashion', label: 'Beauty and Fashion' },
    { value: 'cooking-and-baking', label: 'Cooking and Baking' },
    { value: 'film-studies', label: 'Film Studies' },
    { value: 'gaming-and-esports', label: 'Gaming and Esports' },
    {
      value: 'gardening-and-horticulture',
      label: 'Gardening and Horticulture',
    },
    { value: 'home-and-diy-projects', label: 'Home and DIY Projects' },
    { value: 'miscellaneous', label: 'Miscellaneous' },
    { value: 'music-and-dance', label: 'Music and Dance' },
    {
      value: 'personal-care-and-services',
      label: 'Personal Care and Services',
    },
    {
      value: 'photography-and-videography',
      label: 'Photography and Videography',
    },
    { value: 'reading', label: 'Reading' },
    { value: 'sports-and-fitness', label: 'Sports and Fitness' },
    { value: 'theater-and-drama', label: 'Theater and Drama' },
    { value: 'travel-and-adventure', label: 'Travel and Adventure' },
  ],
  other: [],
  'personal-development': [
    { value: 'basics-of-law', label: 'Basics of Law' },
    { value: 'career-development', label: 'Career Development' },
    { value: 'critical-thinking', label: 'Critical Thinking' },
    { value: 'creativity-and-innovation', label: 'Creativity and Innovation' },
    { value: 'digital-literacy', label: 'Digital Literacy' },
    { value: 'health-and-wellness', label: 'Health and Wellness' },
    { value: 'parenting', label: 'Parenting' },
    {
      value: 'personal-finance-and-investing',
      label: 'Personal Finance and Investing',
    },
    { value: 'real-estate-management', label: 'Real Estate Management' },
    { value: 'relationships', label: 'Relationships' },
    { value: 'soft-skills', label: 'Soft Skills' },
    { value: 'study-skills', label: 'Study Skills' },
    {
      value: 'yoga-mindfulness-and-meditation',
      label: 'Yoga, Mindfulness and Meditation',
    },
  ],
  'teaching-and-learning': [
    {
      value: 'curriculum-design-and-development',
      label: 'Curriculum Design and Development',
    },
    { value: 'distance-learning', label: 'Distance Learning' },
    { value: 'educational-technology', label: 'Educational Technology' },
    { value: 'pedagogy', label: 'Pedagogy' },
    {
      value: 'stepik-platform-and-online-course-creation',
      label: 'Stepik Platform and Online Course Creation',
    },
    { value: 'summer-camps', label: 'Summer Camps' },
  ],
  'technology-and-innovation': [
    { value: '3d-printing', label: '3D Printing' },
    { value: 'artificial-intelligence', label: 'Artificial Intelligence' },
    { value: 'bioinformatics', label: 'Bioinformatics' },
    { value: 'biotechnology', label: 'Biotechnology' },
    { value: 'blockchain-development', label: 'Blockchain Development' },
    { value: 'cybersecurity', label: 'Cybersecurity' },
    { value: 'internet-of-things', label: 'Internet of Things' },
    { value: 'nanotechnology', label: 'Nanotechnology' },
    { value: 'robotics-and-automation', label: 'Robotics and Automation' },
    { value: 'triz', label: 'TRIZ' },
    {
      value: 'virtual-reality-and-augmented-reality',
      label: 'Virtual Reality and Augmented Reality',
    },
  ],
  'test-preparation': [
    { value: 'certification-preparation', label: 'Certification Preparation' },
    {
      value: 'driving-and-vehicle-operation',
      label: 'Driving and Vehicle Operation',
    },
    {
      value: 'english-language-exam-preparation',
      label: 'English Language Exam Preparation',
    },
    {
      value: 'olympiads-and-competitive-programming',
      label: 'Olympiads and Competitive Programming',
    },
    { value: 'school-final-exams', label: 'School Final Exams' },
  ],
};
